trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: git
      name: build.ci-common
  repositories:
  - repository: github_9spokes_go
    type: github
    name: 9spokes/go
    endpoint: 9spokes.github.com

extends:
  template: go/main.yml@templates
  parameters:
    buildArgs: -a -installsuffix cgo -v ./...
    syncToGithub: true
    goGetArgs: -d ./...
