trigger:
- master

queue:
  name: "kubernetes-vsts-agents"

steps:

- task: DownloadSecureFile@1
  displayName: "Download SSH Private Key for GitHub"
  name: "Github"
  inputs:
      secureFile: "Github"

- script: |
    git remote add github git@github.com:9spokes/go.git
    test -d ~/.ssh || mkdir -p ~/.ssh
    mv $AGENT_TEMPDIRECTORY/Github ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    printf "Host github.com\n  StrictHostKeyChecking no" > ~/.ssh/config
  displayName: 'Configure SSH'

- script: |
    git push github master
  displayName: 'Sync to Github'
