trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: git
      name: build.ci-common

extends:
  template: go/main.yml@templates
  parameters:
    buildArgs: -a -installsuffix cgo -v ./...
    syncToGithub: true
    goGetArgs: -d ./...
