// Code generated by "enumer -type=TransactionType -json"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TransactionTypeName = "UncategorisedCashChequePurchaseBillPaymentAutomaticPaymentFeeAdjustment"

var _TransactionTypeIndex = [...]uint8{0, 13, 17, 23, 31, 42, 58, 61, 71}

const _TransactionTypeLowerName = "uncategorisedcashchequepurchasebillpaymentautomaticpaymentfeeadjustment"

func (i TransactionType) String() string {
	if i < 0 || i >= TransactionType(len(_TransactionTypeIndex)-1) {
		return fmt.Sprintf("TransactionType(%d)", i)
	}
	return _TransactionTypeName[_TransactionTypeIndex[i]:_TransactionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TransactionTypeNoOp() {
	var x [1]struct{}
	_ = x[Uncategorised-(0)]
	_ = x[Cash-(1)]
	_ = x[Cheque-(2)]
	_ = x[Purchase-(3)]
	_ = x[BillPayment-(4)]
	_ = x[AutomaticPayment-(5)]
	_ = x[Fee-(6)]
	_ = x[Adjustment-(7)]
}

var _TransactionTypeValues = []TransactionType{Uncategorised, Cash, Cheque, Purchase, BillPayment, AutomaticPayment, Fee, Adjustment}

var _TransactionTypeNameToValueMap = map[string]TransactionType{
	_TransactionTypeName[0:13]:       Uncategorised,
	_TransactionTypeLowerName[0:13]:  Uncategorised,
	_TransactionTypeName[13:17]:      Cash,
	_TransactionTypeLowerName[13:17]: Cash,
	_TransactionTypeName[17:23]:      Cheque,
	_TransactionTypeLowerName[17:23]: Cheque,
	_TransactionTypeName[23:31]:      Purchase,
	_TransactionTypeLowerName[23:31]: Purchase,
	_TransactionTypeName[31:42]:      BillPayment,
	_TransactionTypeLowerName[31:42]: BillPayment,
	_TransactionTypeName[42:58]:      AutomaticPayment,
	_TransactionTypeLowerName[42:58]: AutomaticPayment,
	_TransactionTypeName[58:61]:      Fee,
	_TransactionTypeLowerName[58:61]: Fee,
	_TransactionTypeName[61:71]:      Adjustment,
	_TransactionTypeLowerName[61:71]: Adjustment,
}

var _TransactionTypeNames = []string{
	_TransactionTypeName[0:13],
	_TransactionTypeName[13:17],
	_TransactionTypeName[17:23],
	_TransactionTypeName[23:31],
	_TransactionTypeName[31:42],
	_TransactionTypeName[42:58],
	_TransactionTypeName[58:61],
	_TransactionTypeName[61:71],
}

// TransactionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TransactionTypeString(s string) (TransactionType, error) {
	if val, ok := _TransactionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TransactionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TransactionType values", s)
}

// TransactionTypeValues returns all values of the enum
func TransactionTypeValues() []TransactionType {
	return _TransactionTypeValues
}

// TransactionTypeStrings returns a slice of all String values of the enum
func TransactionTypeStrings() []string {
	strs := make([]string, len(_TransactionTypeNames))
	copy(strs, _TransactionTypeNames)
	return strs
}

// IsATransactionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TransactionType) IsATransactionType() bool {
	for _, v := range _TransactionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TransactionType
func (i TransactionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TransactionType
func (i *TransactionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TransactionType should be a string, got %s", data)
	}

	var err error
	*i, err = TransactionTypeString(s)
	return err
}
